---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - npu.ai
  resources:
  - npuclusterpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - npu.ai
  resources:
  - npuclusterpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - npu.ai
  resources:
  - npuclusterpolicies/status
  verbs:
  - get
  - patch
  - update
