apiVersion: npu.ai/v1alpha1
kind: NPUClusterPolicy
metadata:
  labels:
    app.kubernetes.io/name: npu-operator
    app.kubernetes.io/managed-by: kustomize
  name: npuclusterpolicy-sample
spec:
  # TODO(user): Add fields here
