//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorClass) DeepCopyInto(out *AcceleratorClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorClass.
func (in *AcceleratorClass) DeepCopy() *AcceleratorClass {
	if in == nil {
		return nil
	}
	out := new(AcceleratorClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorClassList) DeepCopyInto(out *AcceleratorClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcceleratorClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorClassList.
func (in *AcceleratorClassList) DeepCopy() *AcceleratorClassList {
	if in == nil {
		return nil
	}
	out := new(AcceleratorClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorClassSpec) DeepCopyInto(out *AcceleratorClassSpec) {
	*out = *in
	in.Requirements.DeepCopyInto(&out.Requirements)
	if in.Mappings != nil {
		in, out := &in.Mappings, &out.Mappings
		*out = make([]AcceleratorMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorClassSpec.
func (in *AcceleratorClassSpec) DeepCopy() *AcceleratorClassSpec {
	if in == nil {
		return nil
	}
	out := new(AcceleratorClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorEvidence) DeepCopyInto(out *AcceleratorEvidence) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorEvidence.
func (in *AcceleratorEvidence) DeepCopy() *AcceleratorEvidence {
	if in == nil {
		return nil
	}
	out := new(AcceleratorEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorEvidence) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorEvidenceList) DeepCopyInto(out *AcceleratorEvidenceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcceleratorEvidence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorEvidenceList.
func (in *AcceleratorEvidenceList) DeepCopy() *AcceleratorEvidenceList {
	if in == nil {
		return nil
	}
	out := new(AcceleratorEvidenceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorEvidenceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorEvidenceSpec) DeepCopyInto(out *AcceleratorEvidenceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorEvidenceSpec.
func (in *AcceleratorEvidenceSpec) DeepCopy() *AcceleratorEvidenceSpec {
	if in == nil {
		return nil
	}
	out := new(AcceleratorEvidenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorEvidenceStatus) DeepCopyInto(out *AcceleratorEvidenceStatus) {
	*out = *in
	out.Fingerprint = in.Fingerprint
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]EvidenceCheck, len(*in))
		copy(*out, *in)
	}
	if in.AdvertisedResources != nil {
		in, out := &in.AdvertisedResources, &out.AdvertisedResources
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorEvidenceStatus.
func (in *AcceleratorEvidenceStatus) DeepCopy() *AcceleratorEvidenceStatus {
	if in == nil {
		return nil
	}
	out := new(AcceleratorEvidenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorHealth) DeepCopyInto(out *AcceleratorHealth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorHealth.
func (in *AcceleratorHealth) DeepCopy() *AcceleratorHealth {
	if in == nil {
		return nil
	}
	out := new(AcceleratorHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorHealth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorHealthList) DeepCopyInto(out *AcceleratorHealthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcceleratorHealth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorHealthList.
func (in *AcceleratorHealthList) DeepCopy() *AcceleratorHealthList {
	if in == nil {
		return nil
	}
	out := new(AcceleratorHealthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorHealthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorHealthPolicy) DeepCopyInto(out *AcceleratorHealthPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorHealthPolicy.
func (in *AcceleratorHealthPolicy) DeepCopy() *AcceleratorHealthPolicy {
	if in == nil {
		return nil
	}
	out := new(AcceleratorHealthPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorHealthPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorHealthPolicyList) DeepCopyInto(out *AcceleratorHealthPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcceleratorHealthPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorHealthPolicyList.
func (in *AcceleratorHealthPolicyList) DeepCopy() *AcceleratorHealthPolicyList {
	if in == nil {
		return nil
	}
	out := new(AcceleratorHealthPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorHealthPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorHealthPolicySpec) DeepCopyInto(out *AcceleratorHealthPolicySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Checks.DeepCopyInto(&out.Checks)
	if in.Remediation != nil {
		in, out := &in.Remediation, &out.Remediation
		*out = make(map[string]RemediationRule, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorHealthPolicySpec.
func (in *AcceleratorHealthPolicySpec) DeepCopy() *AcceleratorHealthPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AcceleratorHealthPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorHealthSpec) DeepCopyInto(out *AcceleratorHealthSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorHealthSpec.
func (in *AcceleratorHealthSpec) DeepCopy() *AcceleratorHealthSpec {
	if in == nil {
		return nil
	}
	out := new(AcceleratorHealthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorHealthStatus) DeepCopyInto(out *AcceleratorHealthStatus) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]HealthSignal, len(*in))
		copy(*out, *in)
	}
	in.DetectedAt.DeepCopyInto(&out.DetectedAt)
	if in.SuspectedAt != nil {
		in, out := &in.SuspectedAt, &out.SuspectedAt
		*out = (*in).DeepCopy()
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]DeviceHealth, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorHealthStatus.
func (in *AcceleratorHealthStatus) DeepCopy() *AcceleratorHealthStatus {
	if in == nil {
		return nil
	}
	out := new(AcceleratorHealthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorMapping) DeepCopyInto(out *AcceleratorMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorMapping.
func (in *AcceleratorMapping) DeepCopy() *AcceleratorMapping {
	if in == nil {
		return nil
	}
	out := new(AcceleratorMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorOperation) DeepCopyInto(out *AcceleratorOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorOperation.
func (in *AcceleratorOperation) DeepCopy() *AcceleratorOperation {
	if in == nil {
		return nil
	}
	out := new(AcceleratorOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorOperationList) DeepCopyInto(out *AcceleratorOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcceleratorOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorOperationList.
func (in *AcceleratorOperationList) DeepCopy() *AcceleratorOperationList {
	if in == nil {
		return nil
	}
	out := new(AcceleratorOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorOperationSpec) DeepCopyInto(out *AcceleratorOperationSpec) {
	*out = *in
	out.Owner = in.Owner
	if in.ResourceKeys != nil {
		in, out := &in.ResourceKeys, &out.ResourceKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorOperationSpec.
func (in *AcceleratorOperationSpec) DeepCopy() *AcceleratorOperationSpec {
	if in == nil {
		return nil
	}
	out := new(AcceleratorOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorOperationStatus) DeepCopyInto(out *AcceleratorOperationStatus) {
	*out = *in
	if in.LeaseExpiry != nil {
		in, out := &in.LeaseExpiry, &out.LeaseExpiry
		*out = (*in).DeepCopy()
	}
	if in.Journal != nil {
		in, out := &in.Journal, &out.Journal
		*out = make([]OperationJournalEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(OperationSnapshot)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorOperationStatus.
func (in *AcceleratorOperationStatus) DeepCopy() *AcceleratorOperationStatus {
	if in == nil {
		return nil
	}
	out := new(AcceleratorOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorPartitionPolicy) DeepCopyInto(out *AcceleratorPartitionPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorPartitionPolicy.
func (in *AcceleratorPartitionPolicy) DeepCopy() *AcceleratorPartitionPolicy {
	if in == nil {
		return nil
	}
	out := new(AcceleratorPartitionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorPartitionPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorPartitionPolicyList) DeepCopyInto(out *AcceleratorPartitionPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcceleratorPartitionPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorPartitionPolicyList.
func (in *AcceleratorPartitionPolicyList) DeepCopy() *AcceleratorPartitionPolicyList {
	if in == nil {
		return nil
	}
	out := new(AcceleratorPartitionPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorPartitionPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorPartitionPolicySpec) DeepCopyInto(out *AcceleratorPartitionPolicySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Layout != nil {
		in, out := &in.Layout, &out.Layout
		*out = make([]PartitionLayout, len(*in))
		copy(*out, *in)
	}
	out.QuiescePolicy = in.QuiescePolicy
	if in.Sharing != nil {
		in, out := &in.Sharing, &out.Sharing
		*out = new(SharingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorPartitionPolicySpec.
func (in *AcceleratorPartitionPolicySpec) DeepCopy() *AcceleratorPartitionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AcceleratorPartitionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorPartitionPolicyStatus) DeepCopyInto(out *AcceleratorPartitionPolicyStatus) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]TargetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ApplyRecords != nil {
		in, out := &in.ApplyRecords, &out.ApplyRecords
		*out = make([]ApplyRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorPartitionPolicyStatus.
func (in *AcceleratorPartitionPolicyStatus) DeepCopy() *AcceleratorPartitionPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AcceleratorPartitionPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorPreferences) DeepCopyInto(out *AcceleratorPreferences) {
	*out = *in
	if in.Vendors != nil {
		in, out := &in.Vendors, &out.Vendors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorPreferences.
func (in *AcceleratorPreferences) DeepCopy() *AcceleratorPreferences {
	if in == nil {
		return nil
	}
	out := new(AcceleratorPreferences)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorRequest) DeepCopyInto(out *AcceleratorRequest) {
	*out = *in
	out.Access = in.Access
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = new(AcceleratorRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Preferences != nil {
		in, out := &in.Preferences, &out.Preferences
		*out = new(AcceleratorPreferences)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorRequest.
func (in *AcceleratorRequest) DeepCopy() *AcceleratorRequest {
	if in == nil {
		return nil
	}
	out := new(AcceleratorRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorRequirements) DeepCopyInto(out *AcceleratorRequirements) {
	*out = *in
	if in.MinimumMemory != nil {
		in, out := &in.MinimumMemory, &out.MinimumMemory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorRequirements.
func (in *AcceleratorRequirements) DeepCopy() *AcceleratorRequirements {
	if in == nil {
		return nil
	}
	out := new(AcceleratorRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorVerificationPolicy) DeepCopyInto(out *AcceleratorVerificationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorVerificationPolicy.
func (in *AcceleratorVerificationPolicy) DeepCopy() *AcceleratorVerificationPolicy {
	if in == nil {
		return nil
	}
	out := new(AcceleratorVerificationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorVerificationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorVerificationPolicyList) DeepCopyInto(out *AcceleratorVerificationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcceleratorVerificationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorVerificationPolicyList.
func (in *AcceleratorVerificationPolicyList) DeepCopy() *AcceleratorVerificationPolicyList {
	if in == nil {
		return nil
	}
	out := new(AcceleratorVerificationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorVerificationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorVerificationPolicySpec) DeepCopyInto(out *AcceleratorVerificationPolicySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.InvalidateOn != nil {
		in, out := &in.InvalidateOn, &out.InvalidateOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DriftGracePeriod != nil {
		in, out := &in.DriftGracePeriod, &out.DriftGracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorVerificationPolicySpec.
func (in *AcceleratorVerificationPolicySpec) DeepCopy() *AcceleratorVerificationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AcceleratorVerificationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorWorkload) DeepCopyInto(out *AcceleratorWorkload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorWorkload.
func (in *AcceleratorWorkload) DeepCopy() *AcceleratorWorkload {
	if in == nil {
		return nil
	}
	out := new(AcceleratorWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorWorkload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorWorkloadList) DeepCopyInto(out *AcceleratorWorkloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcceleratorWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorWorkloadList.
func (in *AcceleratorWorkloadList) DeepCopy() *AcceleratorWorkloadList {
	if in == nil {
		return nil
	}
	out := new(AcceleratorWorkloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcceleratorWorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorWorkloadSpec) DeepCopyInto(out *AcceleratorWorkloadSpec) {
	*out = *in
	in.Accelerator.DeepCopyInto(&out.Accelerator)
	in.Workload.DeepCopyInto(&out.Workload)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorWorkloadSpec.
func (in *AcceleratorWorkloadSpec) DeepCopy() *AcceleratorWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(AcceleratorWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorWorkloadStatus) DeepCopyInto(out *AcceleratorWorkloadStatus) {
	*out = *in
	if in.Resolved != nil {
		in, out := &in.Resolved, &out.Resolved
		*out = new(ResolvedAllocation)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rejection != nil {
		in, out := &in.Rejection, &out.Rejection
		*out = new(WorkloadRejection)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorWorkloadStatus.
func (in *AcceleratorWorkloadStatus) DeepCopy() *AcceleratorWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(AcceleratorWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessSpec) DeepCopyInto(out *AccessSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessSpec.
func (in *AccessSpec) DeepCopy() *AccessSpec {
	if in == nil {
		return nil
	}
	out := new(AccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvertisementStatus) DeepCopyInto(out *AdvertisementStatus) {
	*out = *in
	if in.AdvertisedResources != nil {
		in, out := &in.AdvertisedResources, &out.AdvertisedResources
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvertisementStatus.
func (in *AdvertisementStatus) DeepCopy() *AdvertisementStatus {
	if in == nil {
		return nil
	}
	out := new(AdvertisementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplyRecord) DeepCopyInto(out *ApplyRecord) {
	*out = *in
	if in.GPUPCIs != nil {
		in, out := &in.GPUPCIs, &out.GPUPCIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplyRecord.
func (in *ApplyRecord) DeepCopy() *ApplyRecord {
	if in == nil {
		return nil
	}
	out := new(ApplyRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendRef) DeepCopyInto(out *BackendRef) {
	*out = *in
	out.Rollback = in.Rollback
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendRef.
func (in *BackendRef) DeepCopy() *BackendRef {
	if in == nil {
		return nil
	}
	out := new(BackendRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DcgmExporterSpec) DeepCopyInto(out *DcgmExporterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DcgmExporterSpec.
func (in *DcgmExporterSpec) DeepCopy() *DcgmExporterSpec {
	if in == nil {
		return nil
	}
	out := new(DcgmExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectorSpec) DeepCopyInto(out *DetectorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectorSpec.
func (in *DetectorSpec) DeepCopy() *DetectorSpec {
	if in == nil {
		return nil
	}
	out := new(DetectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceEntry) DeepCopyInto(out *DeviceEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceEntry.
func (in *DeviceEntry) DeepCopy() *DeviceEntry {
	if in == nil {
		return nil
	}
	out := new(DeviceEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceHealth) DeepCopyInto(out *DeviceHealth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceHealth.
func (in *DeviceHealth) DeepCopy() *DeviceHealth {
	if in == nil {
		return nil
	}
	out := new(DeviceHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceStatus) DeepCopyInto(out *DeviceStatus) {
	*out = *in
	in.PartitionCapability.DeepCopyInto(&out.PartitionCapability)
	out.SharingCapability = in.SharingCapability
	out.IsolationCapability = in.IsolationCapability
	if in.AllocationAPIs != nil {
		in, out := &in.AllocationAPIs, &out.AllocationAPIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Operations = in.Operations
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceStatus.
func (in *DeviceStatus) DeepCopy() *DeviceStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverInstallPolicy) DeepCopyInto(out *DriverInstallPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverInstallPolicy.
func (in *DriverInstallPolicy) DeepCopy() *DriverInstallPolicy {
	if in == nil {
		return nil
	}
	out := new(DriverInstallPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DriverInstallPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverInstallPolicyList) DeepCopyInto(out *DriverInstallPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DriverInstallPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverInstallPolicyList.
func (in *DriverInstallPolicyList) DeepCopy() *DriverInstallPolicyList {
	if in == nil {
		return nil
	}
	out := new(DriverInstallPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DriverInstallPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverInstallPolicySpec) DeepCopyInto(out *DriverInstallPolicySpec) {
	*out = *in
	in.Driver.DeepCopyInto(&out.Driver)
	if in.Toolkit != nil {
		in, out := &in.Toolkit, &out.Toolkit
		*out = new(ToolkitSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.KernelAllowlist != nil {
		in, out := &in.KernelAllowlist, &out.KernelAllowlist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.JobOverrides != nil {
		in, out := &in.JobOverrides, &out.JobOverrides
		*out = new(JobOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UpgradePolicy != nil {
		in, out := &in.UpgradePolicy, &out.UpgradePolicy
		*out = new(UpgradePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.VerifiedVersions != nil {
		in, out := &in.VerifiedVersions, &out.VerifiedVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverInstallPolicySpec.
func (in *DriverInstallPolicySpec) DeepCopy() *DriverInstallPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DriverInstallPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverSpec) DeepCopyInto(out *DriverSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]KV, len(*in))
		copy(*out, *in)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraHostMounts != nil {
		in, out := &in.ExtraHostMounts, &out.ExtraHostMounts
		*out = make([]HostPathMount, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverSpec.
func (in *DriverSpec) DeepCopy() *DriverSpec {
	if in == nil {
		return nil
	}
	out := new(DriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverUpgradeState) DeepCopyInto(out *DriverUpgradeState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverUpgradeState.
func (in *DriverUpgradeState) DeepCopy() *DriverUpgradeState {
	if in == nil {
		return nil
	}
	out := new(DriverUpgradeState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DriverUpgradeState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverUpgradeStateList) DeepCopyInto(out *DriverUpgradeStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DriverUpgradeState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverUpgradeStateList.
func (in *DriverUpgradeStateList) DeepCopy() *DriverUpgradeStateList {
	if in == nil {
		return nil
	}
	out := new(DriverUpgradeStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DriverUpgradeStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverUpgradeStateSpec) DeepCopyInto(out *DriverUpgradeStateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverUpgradeStateSpec.
func (in *DriverUpgradeStateSpec) DeepCopy() *DriverUpgradeStateSpec {
	if in == nil {
		return nil
	}
	out := new(DriverUpgradeStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverUpgradeStateStatus) DeepCopyInto(out *DriverUpgradeStateStatus) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	in.RebootRequestedTime.DeepCopyInto(&out.RebootRequestedTime)
	if in.QuiescedDeployments != nil {
		in, out := &in.QuiescedDeployments, &out.QuiescedDeployments
		*out = make([]QuiescedDeployment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverUpgradeStateStatus.
func (in *DriverUpgradeStateStatus) DeepCopy() *DriverUpgradeStateStatus {
	if in == nil {
		return nil
	}
	out := new(DriverUpgradeStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentFingerprint) DeepCopyInto(out *EnvironmentFingerprint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentFingerprint.
func (in *EnvironmentFingerprint) DeepCopy() *EnvironmentFingerprint {
	if in == nil {
		return nil
	}
	out := new(EnvironmentFingerprint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceCheck) DeepCopyInto(out *EvidenceCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceCheck.
func (in *EvidenceCheck) DeepCopy() *EvidenceCheck {
	if in == nil {
		return nil
	}
	out := new(EvidenceCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FuriosaSpec) DeepCopyInto(out *FuriosaSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Rngd.DeepCopyInto(&out.Rngd)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FuriosaSpec.
func (in *FuriosaSpec) DeepCopy() *FuriosaSpec {
	if in == nil {
		return nil
	}
	out := new(FuriosaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthChecks) DeepCopyInto(out *HealthChecks) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthChecks.
func (in *HealthChecks) DeepCopy() *HealthChecks {
	if in == nil {
		return nil
	}
	out := new(HealthChecks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthSignal) DeepCopyInto(out *HealthSignal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthSignal.
func (in *HealthSignal) DeepCopy() *HealthSignal {
	if in == nil {
		return nil
	}
	out := new(HealthSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostPathMount) DeepCopyInto(out *HostPathMount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostPathMount.
func (in *HostPathMount) DeepCopy() *HostPathMount {
	if in == nil {
		return nil
	}
	out := new(HostPathMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IsolationCapability) DeepCopyInto(out *IsolationCapability) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IsolationCapability.
func (in *IsolationCapability) DeepCopy() *IsolationCapability {
	if in == nil {
		return nil
	}
	out := new(IsolationCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobOverrides) DeepCopyInto(out *JobOverrides) {
	*out = *in
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
	if in.BackoffLimit != nil {
		in, out := &in.BackoffLimit, &out.BackoffLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobOverrides.
func (in *JobOverrides) DeepCopy() *JobOverrides {
	if in == nil {
		return nil
	}
	out := new(JobOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KV) DeepCopyInto(out *KV) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KV.
func (in *KV) DeepCopy() *KV {
	if in == nil {
		return nil
	}
	out := new(KV)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPSSpec) DeepCopyInto(out *MPSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPSSpec.
func (in *MPSSpec) DeepCopy() *MPSSpec {
	if in == nil {
		return nil
	}
	out := new(MPSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NPUClusterPolicy) DeepCopyInto(out *NPUClusterPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NPUClusterPolicy.
func (in *NPUClusterPolicy) DeepCopy() *NPUClusterPolicy {
	if in == nil {
		return nil
	}
	out := new(NPUClusterPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NPUClusterPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NPUClusterPolicyList) DeepCopyInto(out *NPUClusterPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NPUClusterPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NPUClusterPolicyList.
func (in *NPUClusterPolicyList) DeepCopy() *NPUClusterPolicyList {
	if in == nil {
		return nil
	}
	out := new(NPUClusterPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NPUClusterPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NPUClusterPolicySpec) DeepCopyInto(out *NPUClusterPolicySpec) {
	*out = *in
	if in.Detector != nil {
		in, out := &in.Detector, &out.Detector
		*out = new(DetectorSpec)
		**out = **in
	}
	in.Nvidia.DeepCopyInto(&out.Nvidia)
	in.Furiosa.DeepCopyInto(&out.Furiosa)
	in.Rebellions.DeepCopyInto(&out.Rebellions)
	in.Tenstorrent.DeepCopyInto(&out.Tenstorrent)
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NPUClusterPolicySpec.
func (in *NPUClusterPolicySpec) DeepCopy() *NPUClusterPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NPUClusterPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NPUClusterPolicyStatus) DeepCopyInto(out *NPUClusterPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NPUClusterPolicyStatus.
func (in *NPUClusterPolicyStatus) DeepCopy() *NPUClusterPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NPUClusterPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDeviceReport) DeepCopyInto(out *NodeDeviceReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDeviceReport.
func (in *NodeDeviceReport) DeepCopy() *NodeDeviceReport {
	if in == nil {
		return nil
	}
	out := new(NodeDeviceReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeDeviceReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDeviceReportList) DeepCopyInto(out *NodeDeviceReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeDeviceReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDeviceReportList.
func (in *NodeDeviceReportList) DeepCopy() *NodeDeviceReportList {
	if in == nil {
		return nil
	}
	out := new(NodeDeviceReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeDeviceReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDeviceReportSpec) DeepCopyInto(out *NodeDeviceReportSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDeviceReportSpec.
func (in *NodeDeviceReportSpec) DeepCopy() *NodeDeviceReportSpec {
	if in == nil {
		return nil
	}
	out := new(NodeDeviceReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDeviceReportStatus) DeepCopyInto(out *NodeDeviceReportStatus) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]DeviceEntry, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		copy(*out, *in)
	}
	if in.Validation != nil {
		in, out := &in.Validation, &out.Validation
		*out = new(ValidationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDeviceReportStatus.
func (in *NodeDeviceReportStatus) DeepCopy() *NodeDeviceReportStatus {
	if in == nil {
		return nil
	}
	out := new(NodeDeviceReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NvidiaSpec) DeepCopyInto(out *NvidiaSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DcgmExporter != nil {
		in, out := &in.DcgmExporter, &out.DcgmExporter
		*out = new(DcgmExporterSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NvidiaSpec.
func (in *NvidiaSpec) DeepCopy() *NvidiaSpec {
	if in == nil {
		return nil
	}
	out := new(NvidiaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedLayoutEntry) DeepCopyInto(out *ObservedLayoutEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedLayoutEntry.
func (in *ObservedLayoutEntry) DeepCopy() *ObservedLayoutEntry {
	if in == nil {
		return nil
	}
	out := new(ObservedLayoutEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationJournalEntry) DeepCopyInto(out *OperationJournalEntry) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationJournalEntry.
func (in *OperationJournalEntry) DeepCopy() *OperationJournalEntry {
	if in == nil {
		return nil
	}
	out := new(OperationJournalEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationOwner) DeepCopyInto(out *OperationOwner) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationOwner.
func (in *OperationOwner) DeepCopy() *OperationOwner {
	if in == nil {
		return nil
	}
	out := new(OperationOwner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationSnapshot) DeepCopyInto(out *OperationSnapshot) {
	*out = *in
	if in.Allocatable != nil {
		in, out := &in.Allocatable, &out.Allocatable
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Geometry != nil {
		in, out := &in.Geometry, &out.Geometry
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationSnapshot.
func (in *OperationSnapshot) DeepCopy() *OperationSnapshot {
	if in == nil {
		return nil
	}
	out := new(OperationSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationStatus) DeepCopyInto(out *OperationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationStatus.
func (in *OperationStatus) DeepCopy() *OperationStatus {
	if in == nil {
		return nil
	}
	out := new(OperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationsStatus) DeepCopyInto(out *OperationsStatus) {
	*out = *in
	out.Apply = in.Apply
	out.Rollback = in.Rollback
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationsStatus.
func (in *OperationsStatus) DeepCopy() *OperationsStatus {
	if in == nil {
		return nil
	}
	out := new(OperationsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartitionCapability) DeepCopyInto(out *PartitionCapability) {
	*out = *in
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]ProfileSupport, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartitionCapability.
func (in *PartitionCapability) DeepCopy() *PartitionCapability {
	if in == nil {
		return nil
	}
	out := new(PartitionCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartitionLayout) DeepCopyInto(out *PartitionLayout) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartitionLayout.
func (in *PartitionLayout) DeepCopy() *PartitionLayout {
	if in == nil {
		return nil
	}
	out := new(PartitionLayout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileSupport) DeepCopyInto(out *ProfileSupport) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileSupport.
func (in *ProfileSupport) DeepCopy() *ProfileSupport {
	if in == nil {
		return nil
	}
	out := new(ProfileSupport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuiescePolicy) DeepCopyInto(out *QuiescePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuiescePolicy.
func (in *QuiescePolicy) DeepCopy() *QuiescePolicy {
	if in == nil {
		return nil
	}
	out := new(QuiescePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuiescedDeployment) DeepCopyInto(out *QuiescedDeployment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuiescedDeployment.
func (in *QuiescedDeployment) DeepCopy() *QuiescedDeployment {
	if in == nil {
		return nil
	}
	out := new(QuiescedDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebellionsSpec) DeepCopyInto(out *RebellionsSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebellionsSpec.
func (in *RebellionsSpec) DeepCopy() *RebellionsSpec {
	if in == nil {
		return nil
	}
	out := new(RebellionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationRule) DeepCopyInto(out *RemediationRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationRule.
func (in *RemediationRule) DeepCopy() *RemediationRule {
	if in == nil {
		return nil
	}
	out := new(RemediationRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedAllocation) DeepCopyInto(out *ResolvedAllocation) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedAllocation.
func (in *ResolvedAllocation) DeepCopy() *ResolvedAllocation {
	if in == nil {
		return nil
	}
	out := new(ResolvedAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedLayoutEntry) DeepCopyInto(out *ResolvedLayoutEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedLayoutEntry.
func (in *ResolvedLayoutEntry) DeepCopy() *ResolvedLayoutEntry {
	if in == nil {
		return nil
	}
	out := new(ResolvedLayoutEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RngdSpec) DeepCopyInto(out *RngdSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RngdSpec.
func (in *RngdSpec) DeepCopy() *RngdSpec {
	if in == nil {
		return nil
	}
	out := new(RngdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollbackInfo) DeepCopyInto(out *RollbackInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollbackInfo.
func (in *RollbackInfo) DeepCopy() *RollbackInfo {
	if in == nil {
		return nil
	}
	out := new(RollbackInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretMount) DeepCopyInto(out *SecretMount) {
	*out = *in
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretMount.
func (in *SecretMount) DeepCopy() *SecretMount {
	if in == nil {
		return nil
	}
	out := new(SecretMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharingCapability) DeepCopyInto(out *SharingCapability) {
	*out = *in
	out.TimeSlicing = in.TimeSlicing
	out.MultiProcess = in.MultiProcess
	out.Brokered = in.Brokered
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharingCapability.
func (in *SharingCapability) DeepCopy() *SharingCapability {
	if in == nil {
		return nil
	}
	out := new(SharingCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharingModeSupport) DeepCopyInto(out *SharingModeSupport) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharingModeSupport.
func (in *SharingModeSupport) DeepCopy() *SharingModeSupport {
	if in == nil {
		return nil
	}
	out := new(SharingModeSupport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharingSpec) DeepCopyInto(out *SharingSpec) {
	*out = *in
	if in.TimeSlicing != nil {
		in, out := &in.TimeSlicing, &out.TimeSlicing
		*out = new(TimeSlicingSpec)
		**out = **in
	}
	if in.MPS != nil {
		in, out := &in.MPS, &out.MPS
		*out = new(MPSSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharingSpec.
func (in *SharingSpec) DeepCopy() *SharingSpec {
	if in == nil {
		return nil
	}
	out := new(SharingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetStatus) DeepCopyInto(out *TargetStatus) {
	*out = *in
	out.Backend = in.Backend
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]DeviceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RequestedLayout != nil {
		in, out := &in.RequestedLayout, &out.RequestedLayout
		*out = make([]PartitionLayout, len(*in))
		copy(*out, *in)
	}
	if in.ResolvedLayout != nil {
		in, out := &in.ResolvedLayout, &out.ResolvedLayout
		*out = make([]ResolvedLayoutEntry, len(*in))
		copy(*out, *in)
	}
	if in.ObservedLayout != nil {
		in, out := &in.ObservedLayout, &out.ObservedLayout
		*out = make([]ObservedLayoutEntry, len(*in))
		copy(*out, *in)
	}
	out.Operations = in.Operations
	in.Advertisement.DeepCopyInto(&out.Advertisement)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetStatus.
func (in *TargetStatus) DeepCopy() *TargetStatus {
	if in == nil {
		return nil
	}
	out := new(TargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenstorrentSpec) DeepCopyInto(out *TenstorrentSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenstorrentSpec.
func (in *TenstorrentSpec) DeepCopy() *TenstorrentSpec {
	if in == nil {
		return nil
	}
	out := new(TenstorrentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSlicingSpec) DeepCopyInto(out *TimeSlicingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSlicingSpec.
func (in *TimeSlicingSpec) DeepCopy() *TimeSlicingSpec {
	if in == nil {
		return nil
	}
	out := new(TimeSlicingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolkitSpec) DeepCopyInto(out *ToolkitSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]KV, len(*in))
		copy(*out, *in)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraHostMounts != nil {
		in, out := &in.ExtraHostMounts, &out.ExtraHostMounts
		*out = make([]HostPathMount, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolkitSpec.
func (in *ToolkitSpec) DeepCopy() *ToolkitSpec {
	if in == nil {
		return nil
	}
	out := new(ToolkitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradePolicy) DeepCopyInto(out *UpgradePolicy) {
	*out = *in
	if in.IdleCooldownSeconds != nil {
		in, out := &in.IdleCooldownSeconds, &out.IdleCooldownSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradePolicy.
func (in *UpgradePolicy) DeepCopy() *UpgradePolicy {
	if in == nil {
		return nil
	}
	out := new(UpgradePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationStatus) DeepCopyInto(out *ValidationStatus) {
	*out = *in
	in.LastRunTime.DeepCopyInto(&out.LastRunTime)
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]ValidationStep, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationStatus.
func (in *ValidationStatus) DeepCopy() *ValidationStatus {
	if in == nil {
		return nil
	}
	out := new(ValidationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationStep) DeepCopyInto(out *ValidationStep) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationStep.
func (in *ValidationStep) DeepCopy() *ValidationStep {
	if in == nil {
		return nil
	}
	out := new(ValidationStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRejection) DeepCopyInto(out *WorkloadRejection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRejection.
func (in *WorkloadRejection) DeepCopy() *WorkloadRejection {
	if in == nil {
		return nil
	}
	out := new(WorkloadRejection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadTemplate) DeepCopyInto(out *WorkloadTemplate) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadTemplate.
func (in *WorkloadTemplate) DeepCopy() *WorkloadTemplate {
	if in == nil {
		return nil
	}
	out := new(WorkloadTemplate)
	in.DeepCopyInto(out)
	return out
}
